language: go
sudo: required

go:
  - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libgtk-3-dev

install:
  - go get github.com/andlabs/ui
  - go get github.com/howeyc/gopass
  - go get github.com/ricardolonga/jsongo